import { MongoClient } from "mongodb";
import dotenv from "dotenv";
dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI!;
if (!MONGODB_URI) {
  console.error("MONGODB_URI is required");
  process.exit(1);
}

const MUSEUMS = [
  {
    id: "louvre",
    title: "The Louvre Museum",
    country: "France",
    city: "Paris",
    category: "Art",
    description: "The world's largest and most visited art museum, home to over 35,000 works including the Mona Lisa and Venus de Milo.",
    history: "Originally built as a medieval fortress in the late 12th century under Philip II, the Louvre evolved into a royal palace before becoming a public museum in 1793 during the French Revolution. Its iconic glass pyramid was added in 1989.",
    ticketPrice: 17,
    ticketType: "Paid",
    openingHours: "Mon, Thu\u2013Sun 9:00\u201318:00 | Wed, Fri 9:00\u201321:45 | Closed Tue",
    rating: 4.8,
    reviewCount: 12450,
    coverImage: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1553522553-f069e6f55b17?w=800&h=500&fit=crop&auto=format",
    ],
    coordinates: { lat: 48.8606, lng: 2.3376 },
    facilities: ["Audio Guide", "Caf\u00e9", "Gift Shop", "Wheelchair Access", "Coat Check", "Wi-Fi"],
    visitorTips: ["Book tickets online to skip queues", "Arrive at opening time for fewer crowds", "Focus on one wing per visit", "The Denon Wing has the most iconic works"],
    featured: true,
  },
  {
    id: "british-museum",
    title: "The British Museum",
    country: "United Kingdom",
    city: "London",
    category: "History",
    description: "One of the world's greatest museums of human history, art, and culture with a collection of over 8 million works spanning two million years.",
    history: "Founded in 1753, the British Museum was the world's first public national museum. Its collection began with the 71,000 objects bequeathed by Sir Hans Sloane. The iconic Great Court with its glass roof was redesigned by Norman Foster and opened in 2000.",
    ticketPrice: 0,
    ticketType: "Free",
    openingHours: "Daily 10:00\u201317:00 | Fri 10:00\u201320:30",
    rating: 4.7,
    reviewCount: 9820,
    coverImage: "https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?w=800&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format",
    ],
    coordinates: { lat: 51.5194, lng: -0.1270 },
    facilities: ["Restaurant", "Library", "Gift Shop", "Wheelchair Access", "Free Wi-Fi"],
    visitorTips: ["The Rosetta Stone and Egyptian mummies are must-sees", "Free entry but donations welcomed", "Pre-book timed entry online"],
    featured: true,
  },
  {
    id: "egyptian-museum",
    title: "Egyptian Museum of Cairo",
    country: "Egypt",
    city: "Cairo",
    category: "Archaeology",
    description: "Home to the world's largest collection of ancient Egyptian antiquities, including the treasures of Tutankhamun.",
    history: "Established in 1902 by the Egyptian government, the Cairo Museum houses over 120,000 items including mummies, sarcophagi, and the stunning gold mask of Tutankhamun discovered by Howard Carter in 1922.",
    ticketPrice: 12,
    ticketType: "Paid",
    openingHours: "Daily 9:00\u201317:00",
    rating: 4.6,
    reviewCount: 7340,
    coverImage: "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&h=500&fit=crop&auto=format",
    ],
    coordinates: { lat: 30.0478, lng: 31.2336 },
    facilities: ["Guided Tours", "Gift Shop", "Caf\u00e9", "Wheelchair Access"],
    visitorTips: ["Hire a licensed guide for deeper context", "The Royal Mummy Room requires separate ticket", "Photography fees apply inside"],
    featured: true,
  },
  {
    id: "tokyo-national",
    title: "Tokyo National Museum",
    country: "Japan",
    city: "Tokyo",
    category: "History",
    description: "Japan's oldest and largest museum, housing the world's largest collection of Japanese art and antiquities.",
    history: "Established in 1872, the Tokyo National Museum is the oldest national museum in Japan. Located in Ueno Park, its grounds contain six buildings housing masterpieces including ancient pottery, samurai swords, and lacquerware spanning over 2,000 years.",
    ticketPrice: 9,
    ticketType: "Paid",
    openingHours: "Tue\u2013Sun 9:30\u201317:00 | Fri\u2013Sat until 21:00 | Closed Mon",
    rating: 4.7,
    reviewCount: 6180,
    coverImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=800&h=500&fit=crop&auto=format",
    ],
    coordinates: { lat: 35.7189, lng: 139.7753 },
    facilities: ["Audio Guide", "Restaurant", "Museum Shop", "Wheelchair Access", "Coin Lockers"],
    visitorTips: ["Visit the Honkan building first for Japanese history", "Cherry blossom season makes the garden spectacular", "Free entry on National Museum Day"],
    featured: true,
  },
  {
    id: "smithsonian-natural-history",
    title: "Smithsonian Natural History",
    country: "USA",
    city: "Washington D.C.",
    category: "Natural History",
    description: "One of the world's premier natural history museums featuring the Hope Diamond, ancient fossils, and a living butterfly pavilion.",
    history: "Opened in 1910, the National Museum of Natural History is part of the Smithsonian Institution. It holds over 145 million specimens including the 45.52-carat Hope Diamond and a 9-ton elephant named Henry in the rotunda.",
    ticketPrice: 0,
    ticketType: "Free",
    openingHours: "Daily 10:00\u201317:30",
    rating: 4.7,
    reviewCount: 11280,
    coverImage: "https://images.unsplash.com/photo-1569434562691-ea8f8d1b5a4b?w=800&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=800&h=500&fit=crop&auto=format",
    ],
    coordinates: { lat: 38.8913, lng: -77.0260 },
    facilities: ["Caf\u00e9", "Gift Shop", "IMAX Theater", "Wheelchair Access", "Family Programs"],
    visitorTips: ["Free admission always", "Butterfly Pavilion has separate admission", "Download the Smithsonian app for self-guided tours"],
    featured: true,
  },
  {
    id: "uffizi",
    title: "Uffizi Gallery",
    country: "Italy",
    city: "Florence",
    category: "Art",
    description: "One of the oldest and most famous art museums in the world, housing the finest collection of Italian Renaissance masterpieces.",
    history: "Built in the 16th century by Giorgio Vasari for Cosimo I de' Medici, the Uffizi Gallery opened to the public in 1769. It houses Botticelli's Birth of Venus and Primavera, along with works by Leonardo da Vinci, Michelangelo, and Raphael.",
    ticketPrice: 20,
    ticketType: "Paid",
    openingHours: "Tue\u2013Sun 8:15\u201318:50 | Closed Mon",
    rating: 4.8,
    reviewCount: 8920,
    coverImage: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&h=500&fit=crop&auto=format",
    ],
    coordinates: { lat: 43.7678, lng: 11.2553 },
    facilities: ["Audio Guide", "Caf\u00e9", "Bookshop", "Wheelchair Access"],
    visitorTips: ["Pre-book tickets \u2014 queues can be 3+ hours long without", "Morning visits are least crowded", "The Botticelli rooms are on the second floor"],
    featured: true,
  },
  {
    id: "national-museum-bangladesh",
    title: "Bangladesh National Museum",
    country: "Bangladesh",
    city: "Dhaka",
    category: "History",
    description: "The premier cultural institution of Bangladesh, showcasing the country's rich history, natural heritage, and artistic traditions.",
    history: "Established in 1913 during British rule, the Bangladesh National Museum houses over 80,000 objects including ancient sculptures from the Pala dynasty, Mughal paintings, coins, manuscripts, and artifacts from the 1971 Liberation War.",
    ticketPrice: 2,
    ticketType: "Paid",
    openingHours: "Sat\u2013Wed 9:30\u201317:00 | Thu 9:30\u201312:00 | Closed Fri",
    rating: 4.3,
    reviewCount: 2140,
    coverImage: "https://images.unsplash.com/photo-1580130544977-1b4aa7e98aed?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 23.7389, lng: 90.3948 },
    facilities: ["Guided Tours", "Library", "Gift Shop"],
    visitorTips: ["Visit the Natural History section for unique flora fauna", "Liberation War gallery is deeply moving", "Photography permitted in most sections"],
    featured: true,
  },
  {
    id: "metropolitan",
    title: "The Metropolitan Museum of Art",
    country: "USA",
    city: "New York",
    category: "Art",
    description: "The largest art museum in the Americas, spanning 5,000 years of world art across 17 curatorial departments.",
    history: "Founded in 1870, the Metropolitan Museum of Art was established by a group of American citizens including business leaders and financiers. Its collection now spans over 2 million works from ancient Egypt to contemporary art.",
    ticketPrice: 30,
    ticketType: "Premium",
    openingHours: "Sun\u2013Thu 10:00\u201317:00 | Fri\u2013Sat 10:00\u201321:00",
    rating: 4.9,
    reviewCount: 14320,
    coverImage: "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=800&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1580673845328-ee53ac43b8b2?w=800&h=500&fit=crop&auto=format",
    ],
    coordinates: { lat: 40.7794, lng: -73.9632 },
    facilities: ["Multiple Restaurants", "Gift Shops", "Audio Guide", "Wheelchair Access", "Coat Check", "Free Wi-Fi"],
    visitorTips: ["The suggested admission is just that \u2014 suggested", "Egyptian Wing with the Temple of Dendur is magnificent", "Rooftop sculpture garden open seasonally"],
    featured: true,
  },
  {
    id: "prado",
    title: "Museo del Prado",
    country: "Spain",
    city: "Madrid",
    category: "Art",
    description: "Spain's national art museum and one of the world's finest collections of European art, featuring Goya, Vel\u00e1zquez, and El Greco.",
    history: "Opened in 1819 under Ferdinand VII, the Prado Museum was originally designed as a natural history museum. It now houses over 20,000 paintings, the largest collection of Goya's works, and Vel\u00e1zquez's Las Meninas.",
    ticketPrice: 15,
    ticketType: "Paid",
    openingHours: "Mon\u2013Sat 10:00\u201320:00 | Sun & Holidays 10:00\u201319:00",
    rating: 4.8,
    reviewCount: 7890,
    coverImage: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 40.4138, lng: -3.6922 },
    facilities: ["Restaurant", "Caf\u00e9", "Bookshop", "Wheelchair Access", "Audio Guide"],
    visitorTips: ["Free entry Mon\u2013Sat 6\u20138pm and Sun 5\u20137pm", "Las Meninas draws the biggest crowds", "Combined ticket with Thyssen and Reina Sof\u00eda available"],
    featured: false,
  },
  {
    id: "science-museum-london",
    title: "Science Museum London",
    country: "United Kingdom",
    city: "London",
    category: "Science",
    description: "Seven floors of groundbreaking science and technology, from steam engines to space capsules and computing history.",
    history: "Opened in 1857 as part of the South Kensington Museum, the Science Museum became independent in 1909. Its collection spans the history of science, technology, medicine, and industry including Stephenson's Rocket locomotive.",
    ticketPrice: 0,
    ticketType: "Free",
    openingHours: "Daily 10:00\u201318:00",
    rating: 4.6,
    reviewCount: 6540,
    coverImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 51.4978, lng: -0.1745 },
    facilities: ["IMAX Cinema", "Restaurants", "Gift Shop", "Wheelchair Access", "Family Spaces"],
    visitorTips: ["IMAX tickets book out fast \u2014 reserve online", "Flight and Space galleries are on upper floors", "Great for school-age children"],
    featured: false,
  },
  {
    id: "acropolis-museum",
    title: "Acropolis Museum",
    country: "Greece",
    city: "Athens",
    category: "Archaeology",
    description: "A stunning modern museum at the foot of the Acropolis, housing artifacts from the Parthenon and ancient Athenian civilization.",
    history: "Opened in 2009, the Acropolis Museum was built to house the surviving antiquities from the Acropolis of Athens. It displays the Parthenon sculptures, caryatids from the Erechtheion, and artifacts spanning 4,000 years of Athenian history.",
    ticketPrice: 10,
    ticketType: "Paid",
    openingHours: "Mon 8:00\u201316:00 | Tue\u2013Sun 8:00\u201320:00 | Fri until 22:00",
    rating: 4.8,
    reviewCount: 5670,
    coverImage: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 37.9715, lng: 23.7257 },
    facilities: ["Restaurant with Acropolis view", "Gift Shop", "Wheelchair Access", "Audio Guide"],
    visitorTips: ["Top-floor restaurant has direct Acropolis views", "Free entry on the first Sunday of the month (Nov\u2013Mar)", "Glass floors reveal ancient ruins beneath the museum"],
    featured: false,
  },
  {
    id: "imperial-war-museum",
    title: "Imperial War Museum",
    country: "United Kingdom",
    city: "London",
    category: "Military",
    description: "Chronicles human conflict from WWI to the present, with powerful exhibits on the Holocaust and the role of women in wartime.",
    history: "Founded in 1917 during World War I to collect and display material relating to the war, the Imperial War Museum opened to the public in 1920. It moved to its current home \u2014 a former psychiatric hospital \u2014 in 1936.",
    ticketPrice: 0,
    ticketType: "Free",
    openingHours: "Daily 10:00\u201318:00",
    rating: 4.7,
    reviewCount: 4890,
    coverImage: "https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 51.4966, lng: -0.1088 },
    facilities: ["Caf\u00e9", "Gift Shop", "Wheelchair Access", "Research Facilities"],
    visitorTips: ["Holocaust Gallery requires emotional preparation", "The First World War galleries are exceptional", "Allow 3+ hours for a thorough visit"],
    featured: false,
  },
  {
    id: "children-museum-indianapolis",
    title: "Children's Museum of Indianapolis",
    country: "USA",
    city: "Indianapolis",
    category: "Children's Museum",
    description: "The world's largest children's museum, with immersive exhibits on science, history, world cultures, and dinosaurs.",
    history: "Founded in 1925, the Children's Museum of Indianapolis has grown to become the world's largest children's museum at 476,000 square feet. Its dinosphere features real dinosaur fossils found by children on museum-sponsored digs.",
    ticketPrice: 22,
    ticketType: "Paid",
    openingHours: "Daily 10:00\u201317:00",
    rating: 4.8,
    reviewCount: 5230,
    coverImage: "https://images.unsplash.com/photo-1560439514-4e9645039924?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 39.7876, lng: -86.1549 },
    facilities: ["Restaurant", "Gift Shops", "Family Restrooms", "Wheelchair Access", "Stroller Rental"],
    visitorTips: ["Plan for a full day \u2014 it's enormous", "Dinosphere is the crowd favorite", "Check the daily show schedule at entry"],
    featured: false,
  },
  {
    id: "pergamon",
    title: "Pergamon Museum",
    country: "Germany",
    city: "Berlin",
    category: "Archaeology",
    description: "Home to monumental ancient architecture including the Pergamon Altar, Ishtar Gate of Babylon, and Market Gate of Miletus.",
    history: "Opened in 1930 on Berlin's Museum Island, the Pergamon Museum was built specifically to house large-scale architectural reconstructions of ancient structures. The Ishtar Gate from Babylon dates to 575 BCE.",
    ticketPrice: 16,
    ticketType: "Paid",
    openingHours: "Daily 10:00\u201318:00 | Thu until 20:00",
    rating: 4.6,
    reviewCount: 6120,
    coverImage: "https://images.unsplash.com/photo-1603436326446-74e2d65f3e72?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 52.5211, lng: 13.3966 },
    facilities: ["Caf\u00e9", "Museum Shop", "Audio Guide", "Wheelchair Access"],
    visitorTips: ["The panorama of ancient Pergamon is breathtaking", "Berlin Museum Pass covers entry", "Main Pergamon Altar hall under renovation until 2027"],
    featured: false,
  },
  {
    id: "national-palace-museum",
    title: "National Palace Museum",
    country: "Taiwan",
    city: "Taipei",
    category: "History",
    description: "Houses the world's most extensive collection of Chinese imperial treasures, spanning 5,000 years of Chinese culture and history.",
    history: "The collection originated from China's imperial palace and was brought to Taiwan in 1949. The museum opened in Taipei in 1965 and holds nearly 700,000 pieces including the famous Jadeite Cabbage and Meat-Shaped Stone.",
    ticketPrice: 10,
    ticketType: "Paid",
    openingHours: "Daily 8:30\u201318:30 | Fri\u2013Sat until 21:00",
    rating: 4.7,
    reviewCount: 4560,
    coverImage: "https://images.unsplash.com/photo-1590123575899-7d0facb2fdb8?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 25.1023, lng: 121.5484 },
    facilities: ["Restaurant", "Caf\u00e9", "Gift Shop", "Audio Guide", "Wheelchair Access"],
    visitorTips: ["The Jadeite Cabbage is tiny but iconic", "Book dining reservation in advance", "Evening visits on weekends are less crowded"],
    featured: false,
  },
  {
    id: "vasa-museum",
    title: "Vasa Museum",
    country: "Sweden",
    city: "Stockholm",
    category: "History",
    description: "The only preserved 17th-century warship in the world, the Vasa sank on its maiden voyage in 1628 and was salvaged in 1961.",
    history: "The Vasa warship was built between 1626 and 1628 for King Gustav II Adolf. It sank in Stockholm Harbor just 1,300 meters into its maiden voyage. Salvaged in 1961 after 333 years on the seabed, it is 95% original material.",
    ticketPrice: 19,
    ticketType: "Paid",
    openingHours: "Daily 10:00\u201317:00 | Jun\u2013Aug until 18:00",
    rating: 4.9,
    reviewCount: 7890,
    coverImage: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 59.3282, lng: 18.0915 },
    facilities: ["Restaurant", "Gift Shop", "Wheelchair Access", "Audio Guide", "Children's Activities"],
    visitorTips: ["The ship itself is overwhelming in scale", "Allow 2\u20133 hours minimum", "Guided tours every hour in summer"],
    featured: false,
  },
  {
    id: "smithsonian-air-space",
    title: "National Air and Space Museum",
    country: "USA",
    city: "Washington D.C.",
    category: "Science",
    description: "The most-visited museum in the world, showcasing aviation and spaceflight from the Wright Brothers to the Space Shuttle.",
    history: "Part of the Smithsonian Institution and opened in 1976 for the US Bicentennial, the National Air and Space Museum on the National Mall holds the Wright Brothers' Flyer, Neil Armstrong's spacesuit, and a moon rock visitors can touch.",
    ticketPrice: 0,
    ticketType: "Free",
    openingHours: "Daily 10:00\u201317:30",
    rating: 4.8,
    reviewCount: 15670,
    coverImage: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 38.8882, lng: -77.0199 },
    facilities: ["Food Court", "Gift Shop", "IMAX", "Planetarium", "Wheelchair Access"],
    visitorTips: ["Touch a real Moon rock in the lobby", "IMAX shows book out \u2014 buy in advance", "The restoration hangar at Udvar-Hazy Center is spectacular"],
    featured: false,
  },
  {
    id: "national-museum-india",
    title: "National Museum of India",
    country: "India",
    city: "New Delhi",
    category: "History",
    description: "India's premier museum, housing a vast collection of art, ornaments, manuscripts, and armor spanning 5,000 years of Indian civilization.",
    history: "Inaugurated in 1949, the National Museum of New Delhi displays over 200,000 works of art spanning 5,000 years of Indian cultural heritage including the Indus Valley Civilization, Mauryan Empire, Mughal era, and modern period.",
    ticketPrice: 20,
    ticketType: "Paid",
    openingHours: "Tue\u2013Sun 10:00\u201318:00 | Closed Mon",
    rating: 4.5,
    reviewCount: 3240,
    coverImage: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 28.6126, lng: 77.2196 },
    facilities: ["Caf\u00e9", "Library", "Gift Shop", "Wheelchair Access", "Guided Tours"],
    visitorTips: ["The Indus Valley gallery is outstanding", "Hire a guide \u2014 labels are minimal", "Photography permitted with camera fee"],
    featured: false,
  },
  {
    id: "rijksmuseum",
    title: "Rijksmuseum",
    country: "Netherlands",
    city: "Amsterdam",
    category: "Art",
    description: "The Netherlands' national museum dedicated to Dutch arts and history, home to Rembrandt's Night Watch and Vermeer's Milkmaid.",
    history: "Founded in 1800 and housed in its current building since 1885, the Rijksmuseum presents 800 years of Dutch and Flemish art. After a decade-long renovation completed in 2013, the museum now welcomes over 2 million visitors annually.",
    ticketPrice: 22,
    ticketType: "Paid",
    openingHours: "Daily 9:00\u201317:00",
    rating: 4.8,
    reviewCount: 8910,
    coverImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 52.3600, lng: 4.8852 },
    facilities: ["Restaurant", "Caf\u00e9", "Bookshop", "Wheelchair Access", "Garden"],
    visitorTips: ["Book tickets well in advance", "The Night Watch has its own dedicated gallery", "The garden is free and beautiful in spring"],
    featured: false,
  },
  {
    id: "hermitage",
    title: "The State Hermitage Museum",
    country: "Russia",
    city: "Saint Petersburg",
    category: "Art",
    description: "One of the largest and oldest museums in the world, occupying the former Winter Palace with over 3 million works of art.",
    history: "Founded in 1764 by Empress Catherine the Great with the acquisition of 255 Dutch and Flemish paintings, the Hermitage now occupies six historic buildings and holds works by Rembrandt, Leonardo, Picasso, and Matisse.",
    ticketPrice: 25,
    ticketType: "Paid",
    openingHours: "Tue\u2013Sun 10:30\u201318:00 | Wed, Fri until 21:00 | Closed Mon",
    rating: 4.8,
    reviewCount: 7230,
    coverImage: "https://images.unsplash.com/photo-1548502499-ef49c3b85c3c?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    coordinates: { lat: 59.9398, lng: 30.3146 },
    facilities: ["Multiple Restaurants", "Gift Shops", "Guided Tours", "Wheelchair Access", "Cloakroom"],
    visitorTips: ["You cannot see everything in one day \u2014 choose a focus", "Free entry on the third Thursday of the month", "Winter Palace alone is worth the visit"],
    featured: false,
  },
];

async function seed() {
  const client = new MongoClient(MONGODB_URI);

  try {
    await client.connect();
    const db = client.db();

    const museumsCol = db.collection("museums");
    await museumsCol.deleteMany({});
    await museumsCol.insertMany(
      MUSEUMS.map((m) => ({ ...m, createdAt: new Date() }))
    );

    await museumsCol.createIndex({ title: "text", description: "text" });
    await museumsCol.createIndex({ country: 1 });
    await museumsCol.createIndex({ category: 1 });
    await museumsCol.createIndex({ rating: -1 });
    await museumsCol.createIndex({ ticketPrice: 1 });
    await museumsCol.createIndex({ featured: 1 });
    await museumsCol.createIndex({ id: 1 }, { unique: true });

    console.log(`[Seed] Inserted ${MUSEUMS.length} museums`);
  } finally {
    await client.close();
  }
}

seed().catch(console.error);
